### ISSUE TITLE
Cool project! Some thoughts.

### ISSUE THREAD

**Issue by rob-p** [ebi-gene-expression-group/snRNA-mapping-rate#1]
Hi,

  I randomly stumbled across this project and it seems pretty interesting!  I just had some basic thoughts about how it looks like `alevin-fry` is currently being run.  One note is that when producing a RAD file for consumption by `alevin-fry` (e.g. [here](https://github.com/ebi-gene-expression-group/snRNA-mapping-rate/blob/4f4f3a900630e4faee5c48349340a4a588bb80e5/main.nf#L734) the  `--keepCBFraction`, `--freqThreshold`, and `--tgMap` parameters are unnecessary.  They affect the behavior of `alevin` itself during quantification, but when `alevin-fry` is being used for quantification they have no effect, since `alevin` is essentially just doing mapping of the reads to the target transcriptome.

  The other thought is that you _may_ want to use the [`--unfiltered-pl`](https://alevin-fry.readthedocs.io/en/latest/generate_permit_list.html) flag during permit list generation, rather than the knee method [here](https://github.com/ebi-gene-expression-group/snRNA-mapping-rate/blob/4f4f3a900630e4faee5c48349340a4a588bb80e5/main.nf#L737) to make the results as comparable as possible to other methods.  Specifically, the other tools (apart from the original `alevin`) make use of the external permit-list (i.e. the so-called whitelist) when processing 10x chromium data.  The knee method performs filtering to derive the permit-list from the data itself, and works when there is no external list of potential barcodes available, but will produce a more stringent filtering (sometimes considerably) than quantifying with the `--unfiltered-pl` option.  Finally, the [`--min-reads <threshold>`](https://alevin-fry.readthedocs.io/en/latest/generate_permit_list.html) option can also be passed to the `generate-permit-list` step if you want to alter the default cutoff for the number of reads that must be present for a cell to be quantified in the output (the default is 10 in the current and recent versions of `alevin-fry`).

Best,
Rob

**Comment by pinin4fjords** [comment]
Thank you very much for that input @rob-p, we really appreciate it! 

For context, @nadjano is an intern we have attempting to address deficiencies in our scRNA-seq pipelines when dealing with snRNAseq. We are attempting to decide whether to just use a different intron-containing reference, or new tools/ pipelines.

There is of course a case for updating our Alevin-driven scRNA pipeline for alevin-fry as well, but that's a question for another day.

**Comment by nadjano** [comment]
Thanks a lot @rob-p! 
Your comments are really helpful 👍 I will definitely include them.

**Comment by rob-p** [comment]
Thanks! I'll be happy to provide feedback should any other questions come up as well (e.g. parsing/interpreting the output of alev-fry's USA mode).

**Comment by DongzeHE** [comment]
Hello all, 

I just fixed a severe bug in the `make_splici_txome` function of pyroe. Please **make sure** that you use the latest version (0.4.0) of pyroe to make the splici references. I apologize for the inconvenience. 

Dongze

**Comment by nadjano** [comment]
Thanks for the notification @DongzeHE! I will change to the latest version.

Best, 
Nadja
